### ISSUE TITLE
Started a new monitoring on top of old

### ISSUE THREAD

**Issue by King-Charming** [truestaking/mccm#2]
Hi, I accidentally started a new monitoring on top of the old and now I keep getting messages:

Error: is not sending is alive messages

I have tried deleting it but it only deleted the new one, how do I shut down the old one?

**Comment by truestaking** [comment]
We are working on a new fix for this, most likely adding a stop button on the telegram bot, and an unsubscribe for the emails, but currently without your server api key, you cannot delete the server account from our backend. Message me on telegram @samarvin or email me silas@truestaking.com your email and/or telegram where you are getting these notifications, and I can manually remove them.

**Comment by truestaking** [comment]
Closing this because the issue was resolved.
